server:
  port: 8818

# file upload
spring.servlet.multipart:
  enabled: true
  max-file-size: 1GB
  max-request-size: 1GB
  location: ${mn.erin.dms.upload_location}

mn:
  erin:
    dms:
      upload_location: ${user.dir}/fsRoot/temp

spring:
  main:
    allow-bean-definition-overriding: true

# mongoDB
spring.data.mongodb.database: dms
spring.data.mongodb.uri: mongodb://localhost:27017/dms
