openapi: 3.0.3
info:
  version: 1.0.0
  title: EES Document REST API
  description: EES Document REST API definitions

servers:
  - url: /documentApi

paths:
  /document-type/get/{organizationId}/{groupId}:
    get:
      summary: returns all document types
      operationId: getDocumentTypes
      tags:
        - DocumentType
      parameters:
        - name: organizationId
          in: path
          description: ID of the organization
          required: true
          schema:
            type: string
        - name: groupId
          in: path
          description: ID of the group
          required: true
          schema:
            type: string
      responses:
        default:
          description: Available document list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypesResponse'

  /document-type/create/{organizationId}:
    post:
      summary: create a document type
      operationId: createDocumentType
      tags:
        - DocumentType
      parameters:
        - name: organizationId
          in: path
          description: ID of the organization
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/DocumentTypePayload'
      responses:
        default:
          description: Document type data JSON model
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CreateDocumentTypeResponse'

components:
  schemas:
    GenericError:
      properties:
        message:
          type: string

    DocumentTypePayload:
      type: object
      properties:
        groupId:
          type: string
        category:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - organizationId
        - groupId
        - category
        - name

    DocumentType:
      type: object
      properties:
        id:
          type: string
        createdBy:
          type: string
        organizationId:
          type: string
        groupId:
          type: string
        category:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - id
        - createdBy
        - organizationId
        - groupId
        - category
        - name

    DocumentTypesResponse:
      properties:
        error:
          $ref: '#/components/schemas/GenericError'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/DocumentType'

    CreateDocumentTypeResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/GenericError'
        id:
          type: string