/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Activity
 */
public class ActivityTest {
    private final Activity model = new Activity();

    /**
     * Model tests for Activity
     */
    @Test
    public void testActivity() {
        // TODO: test Activity
    }

    /**
     * Test the property 'postPersonId'
     */
    @Test
    public void postPersonIdTest() {
        // TODO: test postPersonId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'postedAt'
     */
    @Test
    public void postedAtTest() {
        // TODO: test postedAt
    }

    /**
     * Test the property 'feedPersonId'
     */
    @Test
    public void feedPersonIdTest() {
        // TODO: test feedPersonId
    }

    /**
     * Test the property 'activitySummary'
     */
    @Test
    public void activitySummaryTest() {
        // TODO: test activitySummary
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

}
