/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ActionParameterDefinition;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ActionDefinition
 */
public class ActionDefinitionTest {
    private final ActionDefinition model = new ActionDefinition();

    /**
     * Model tests for ActionDefinition
     */
    @Test
    public void testActionDefinition() {
        // TODO: test ActionDefinition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'applicableTypes'
     */
    @Test
    public void applicableTypesTest() {
        // TODO: test applicableTypes
    }

    /**
     * Test the property 'trackStatus'
     */
    @Test
    public void trackStatusTest() {
        // TODO: test trackStatus
    }

    /**
     * Test the property 'parameterDefinitions'
     */
    @Test
    public void parameterDefinitionsTest() {
        // TODO: test parameterDefinitions
    }

}
