/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContentInfo
 */
public class ContentInfoTest {
    private final ContentInfo model = new ContentInfo();

    /**
     * Model tests for ContentInfo
     */
    @Test
    public void testContentInfo() {
        // TODO: test ContentInfo
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'mimeTypeName'
     */
    @Test
    public void mimeTypeNameTest() {
        // TODO: test mimeTypeName
    }

    /**
     * Test the property 'sizeInBytes'
     */
    @Test
    public void sizeInBytesTest() {
        // TODO: test sizeInBytes
    }

    /**
     * Test the property 'encoding'
     */
    @Test
    public void encodingTest() {
        // TODO: test encoding
    }

}
