/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Download
 */
public class DownloadTest {
    private final Download model = new Download();

    /**
     * Model tests for Download
     */
    @Test
    public void testDownload() {
        // TODO: test Download
    }

    /**
     * Test the property 'filesAdded'
     */
    @Test
    public void filesAddedTest() {
        // TODO: test filesAdded
    }

    /**
     * Test the property 'bytesAdded'
     */
    @Test
    public void bytesAddedTest() {
        // TODO: test bytesAdded
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'totalFiles'
     */
    @Test
    public void totalFilesTest() {
        // TODO: test totalFiles
    }

    /**
     * Test the property 'totalBytes'
     */
    @Test
    public void totalBytesTest() {
        // TODO: test totalBytes
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
