/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GroupMember;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupMemberEntry
 */
public class GroupMemberEntryTest {
    private final GroupMemberEntry model = new GroupMemberEntry();

    /**
     * Model tests for GroupMemberEntry
     */
    @Test
    public void testGroupMemberEntry() {
        // TODO: test GroupMemberEntry
    }

    /**
     * Test the property 'entry'
     */
    @Test
    public void entryTest() {
        // TODO: test entry
    }

}
