/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ChildAssociationInfo;
import org.openapitools.client.model.ContentInfo;
import org.openapitools.client.model.Definition;
import org.openapitools.client.model.Node;
import org.openapitools.client.model.NodeChildAssociationAllOf;
import org.openapitools.client.model.PathInfo;
import org.openapitools.client.model.PermissionsInfo;
import org.openapitools.client.model.UserInfo;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NodeChildAssociation
 */
public class NodeChildAssociationTest {
    private final NodeChildAssociation model = new NodeChildAssociation();

    /**
     * Model tests for NodeChildAssociation
     */
    @Test
    public void testNodeChildAssociation() {
        // TODO: test NodeChildAssociation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodeType'
     */
    @Test
    public void nodeTypeTest() {
        // TODO: test nodeType
    }

    /**
     * Test the property 'isFolder'
     */
    @Test
    public void isFolderTest() {
        // TODO: test isFolder
    }

    /**
     * Test the property 'isFile'
     */
    @Test
    public void isFileTest() {
        // TODO: test isFile
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'modifiedAt'
     */
    @Test
    public void modifiedAtTest() {
        // TODO: test modifiedAt
    }

    /**
     * Test the property 'modifiedByUser'
     */
    @Test
    public void modifiedByUserTest() {
        // TODO: test modifiedByUser
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'createdByUser'
     */
    @Test
    public void createdByUserTest() {
        // TODO: test createdByUser
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'isLink'
     */
    @Test
    public void isLinkTest() {
        // TODO: test isLink
    }

    /**
     * Test the property 'isFavorite'
     */
    @Test
    public void isFavoriteTest() {
        // TODO: test isFavorite
    }

    /**
     * Test the property 'isDirectLinkEnabled'
     */
    @Test
    public void isDirectLinkEnabledTest() {
        // TODO: test isDirectLinkEnabled
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'aspectNames'
     */
    @Test
    public void aspectNamesTest() {
        // TODO: test aspectNames
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'allowableOperations'
     */
    @Test
    public void allowableOperationsTest() {
        // TODO: test allowableOperations
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'definition'
     */
    @Test
    public void definitionTest() {
        // TODO: test definition
    }

    /**
     * Test the property 'association'
     */
    @Test
    public void associationTest() {
        // TODO: test association
    }

}
