/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PermissionElement
 */
public class PermissionElementTest {
    private final PermissionElement model = new PermissionElement();

    /**
     * Model tests for PermissionElement
     */
    @Test
    public void testPermissionElement() {
        // TODO: test PermissionElement
    }

    /**
     * Test the property 'authorityId'
     */
    @Test
    public void authorityIdTest() {
        // TODO: test authorityId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'accessStatus'
     */
    @Test
    public void accessStatusTest() {
        // TODO: test accessStatus
    }

}
