/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * Activities describe any past activity in a site, for example creating an item of content, commenting on a node, liking an item of content. 
 */
@ApiModel(description = "Activities describe any past activity in a site, for example creating an item of content, commenting on a node, liking an item of content. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class Activity {
  public static final String SERIALIZED_NAME_POST_PERSON_ID = "postPersonId";
  @SerializedName(SERIALIZED_NAME_POST_PERSON_ID)
  private String postPersonId;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_SITE_ID = "siteId";
  @SerializedName(SERIALIZED_NAME_SITE_ID)
  private String siteId;

  public static final String SERIALIZED_NAME_POSTED_AT = "postedAt";
  @SerializedName(SERIALIZED_NAME_POSTED_AT)
  private OffsetDateTime postedAt;

  public static final String SERIALIZED_NAME_FEED_PERSON_ID = "feedPersonId";
  @SerializedName(SERIALIZED_NAME_FEED_PERSON_ID)
  private String feedPersonId;

  public static final String SERIALIZED_NAME_ACTIVITY_SUMMARY = "activitySummary";
  @SerializedName(SERIALIZED_NAME_ACTIVITY_SUMMARY)
  private Map<String, String> activitySummary = null;

  public static final String SERIALIZED_NAME_ACTIVITY_TYPE = "activityType";
  @SerializedName(SERIALIZED_NAME_ACTIVITY_TYPE)
  private String activityType;


  public Activity postPersonId(String postPersonId) {
    
    this.postPersonId = postPersonId;
    return this;
  }

   /**
   * The id of the person who performed the activity
   * @return postPersonId
  **/
  @ApiModelProperty(required = true, value = "The id of the person who performed the activity")

  public String getPostPersonId() {
    return postPersonId;
  }


  public void setPostPersonId(String postPersonId) {
    this.postPersonId = postPersonId;
  }


  public Activity id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique id of the activity
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The unique id of the activity")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Activity siteId(String siteId) {
    
    this.siteId = siteId;
    return this;
  }

   /**
   * The unique id of the site on which the activity was performed
   * @return siteId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique id of the site on which the activity was performed")

  public String getSiteId() {
    return siteId;
  }


  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }


  public Activity postedAt(OffsetDateTime postedAt) {
    
    this.postedAt = postedAt;
    return this;
  }

   /**
   * The date time at which the activity was performed
   * @return postedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date time at which the activity was performed")

  public OffsetDateTime getPostedAt() {
    return postedAt;
  }


  public void setPostedAt(OffsetDateTime postedAt) {
    this.postedAt = postedAt;
  }


  public Activity feedPersonId(String feedPersonId) {
    
    this.feedPersonId = feedPersonId;
    return this;
  }

   /**
   * The feed on which this activity was posted
   * @return feedPersonId
  **/
  @ApiModelProperty(required = true, value = "The feed on which this activity was posted")

  public String getFeedPersonId() {
    return feedPersonId;
  }


  public void setFeedPersonId(String feedPersonId) {
    this.feedPersonId = feedPersonId;
  }


  public Activity activitySummary(Map<String, String> activitySummary) {
    
    this.activitySummary = activitySummary;
    return this;
  }

  public Activity putActivitySummaryItem(String key, String activitySummaryItem) {
    if (this.activitySummary == null) {
      this.activitySummary = new HashMap<String, String>();
    }
    this.activitySummary.put(key, activitySummaryItem);
    return this;
  }

   /**
   * An object summarizing the activity
   * @return activitySummary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An object summarizing the activity")

  public Map<String, String> getActivitySummary() {
    return activitySummary;
  }


  public void setActivitySummary(Map<String, String> activitySummary) {
    this.activitySummary = activitySummary;
  }


  public Activity activityType(String activityType) {
    
    this.activityType = activityType;
    return this;
  }

   /**
   * The type of the activity posted
   * @return activityType
  **/
  @ApiModelProperty(required = true, value = "The type of the activity posted")

  public String getActivityType() {
    return activityType;
  }


  public void setActivityType(String activityType) {
    this.activityType = activityType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity activity = (Activity) o;
    return Objects.equals(this.postPersonId, activity.postPersonId) &&
        Objects.equals(this.id, activity.id) &&
        Objects.equals(this.siteId, activity.siteId) &&
        Objects.equals(this.postedAt, activity.postedAt) &&
        Objects.equals(this.feedPersonId, activity.feedPersonId) &&
        Objects.equals(this.activitySummary, activity.activitySummary) &&
        Objects.equals(this.activityType, activity.activityType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postPersonId, id, siteId, postedAt, feedPersonId, activitySummary, activityType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");
    sb.append("    postPersonId: ").append(toIndentedString(postPersonId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    postedAt: ").append(toIndentedString(postedAt)).append("\n");
    sb.append("    feedPersonId: ").append(toIndentedString(feedPersonId)).append("\n");
    sb.append("    activitySummary: ").append(toIndentedString(activitySummary)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

