/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ErrorError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class ErrorError {
  public static final String SERIALIZED_NAME_ERROR_KEY = "errorKey";
  @SerializedName(SERIALIZED_NAME_ERROR_KEY)
  private String errorKey;

  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private Integer statusCode;

  public static final String SERIALIZED_NAME_BRIEF_SUMMARY = "briefSummary";
  @SerializedName(SERIALIZED_NAME_BRIEF_SUMMARY)
  private String briefSummary;

  public static final String SERIALIZED_NAME_STACK_TRACE = "stackTrace";
  @SerializedName(SERIALIZED_NAME_STACK_TRACE)
  private String stackTrace;

  public static final String SERIALIZED_NAME_DESCRIPTION_U_R_L = "descriptionURL";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_U_R_L)
  private String descriptionURL;

  public static final String SERIALIZED_NAME_LOG_ID = "logId";
  @SerializedName(SERIALIZED_NAME_LOG_ID)
  private String logId;


  public ErrorError errorKey(String errorKey) {
    
    this.errorKey = errorKey;
    return this;
  }

   /**
   * Get errorKey
   * @return errorKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getErrorKey() {
    return errorKey;
  }


  public void setErrorKey(String errorKey) {
    this.errorKey = errorKey;
  }


  public ErrorError statusCode(Integer statusCode) {
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }


  public ErrorError briefSummary(String briefSummary) {
    
    this.briefSummary = briefSummary;
    return this;
  }

   /**
   * Get briefSummary
   * @return briefSummary
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBriefSummary() {
    return briefSummary;
  }


  public void setBriefSummary(String briefSummary) {
    this.briefSummary = briefSummary;
  }


  public ErrorError stackTrace(String stackTrace) {
    
    this.stackTrace = stackTrace;
    return this;
  }

   /**
   * Get stackTrace
   * @return stackTrace
  **/
  @ApiModelProperty(required = true, value = "")

  public String getStackTrace() {
    return stackTrace;
  }


  public void setStackTrace(String stackTrace) {
    this.stackTrace = stackTrace;
  }


  public ErrorError descriptionURL(String descriptionURL) {
    
    this.descriptionURL = descriptionURL;
    return this;
  }

   /**
   * Get descriptionURL
   * @return descriptionURL
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDescriptionURL() {
    return descriptionURL;
  }


  public void setDescriptionURL(String descriptionURL) {
    this.descriptionURL = descriptionURL;
  }


  public ErrorError logId(String logId) {
    
    this.logId = logId;
    return this;
  }

   /**
   * Get logId
   * @return logId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogId() {
    return logId;
  }


  public void setLogId(String logId) {
    this.logId = logId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorError errorError = (ErrorError) o;
    return Objects.equals(this.errorKey, errorError.errorKey) &&
        Objects.equals(this.statusCode, errorError.statusCode) &&
        Objects.equals(this.briefSummary, errorError.briefSummary) &&
        Objects.equals(this.stackTrace, errorError.stackTrace) &&
        Objects.equals(this.descriptionURL, errorError.descriptionURL) &&
        Objects.equals(this.logId, errorError.logId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorKey, statusCode, briefSummary, stackTrace, descriptionURL, logId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorError {\n");
    sb.append("    errorKey: ").append(toIndentedString(errorKey)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    briefSummary: ").append(toIndentedString(briefSummary)).append("\n");
    sb.append("    stackTrace: ").append(toIndentedString(stackTrace)).append("\n");
    sb.append("    descriptionURL: ").append(toIndentedString(descriptionURL)).append("\n");
    sb.append("    logId: ").append(toIndentedString(logId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

