/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ContentInfo;
import org.openapitools.client.model.Definition;
import org.openapitools.client.model.PathInfo;
import org.openapitools.client.model.PermissionsInfo;
import org.openapitools.client.model.UserInfo;
import org.threeten.bp.OffsetDateTime;

/**
 * Node
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class Node {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NODE_TYPE = "nodeType";
  @SerializedName(SERIALIZED_NAME_NODE_TYPE)
  private String nodeType;

  public static final String SERIALIZED_NAME_IS_FOLDER = "isFolder";
  @SerializedName(SERIALIZED_NAME_IS_FOLDER)
  private Boolean isFolder;

  public static final String SERIALIZED_NAME_IS_FILE = "isFile";
  @SerializedName(SERIALIZED_NAME_IS_FILE)
  private Boolean isFile;

  public static final String SERIALIZED_NAME_IS_LOCKED = "isLocked";
  @SerializedName(SERIALIZED_NAME_IS_LOCKED)
  private Boolean isLocked = false;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY_USER = "modifiedByUser";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY_USER)
  private UserInfo modifiedByUser;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY_USER = "createdByUser";
  @SerializedName(SERIALIZED_NAME_CREATED_BY_USER)
  private UserInfo createdByUser;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private String parentId;

  public static final String SERIALIZED_NAME_IS_LINK = "isLink";
  @SerializedName(SERIALIZED_NAME_IS_LINK)
  private Boolean isLink;

  public static final String SERIALIZED_NAME_IS_FAVORITE = "isFavorite";
  @SerializedName(SERIALIZED_NAME_IS_FAVORITE)
  private Boolean isFavorite;

  public static final String SERIALIZED_NAME_IS_DIRECT_LINK_ENABLED = "isDirectLinkEnabled";
  @SerializedName(SERIALIZED_NAME_IS_DIRECT_LINK_ENABLED)
  private Boolean isDirectLinkEnabled;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private ContentInfo content;

  public static final String SERIALIZED_NAME_ASPECT_NAMES = "aspectNames";
  @SerializedName(SERIALIZED_NAME_ASPECT_NAMES)
  private List<String> aspectNames = null;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Object properties;

  public static final String SERIALIZED_NAME_ALLOWABLE_OPERATIONS = "allowableOperations";
  @SerializedName(SERIALIZED_NAME_ALLOWABLE_OPERATIONS)
  private List<String> allowableOperations = null;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private PathInfo path;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private PermissionsInfo permissions;

  public static final String SERIALIZED_NAME_DEFINITION = "definition";
  @SerializedName(SERIALIZED_NAME_DEFINITION)
  private Definition definition;


  public Node id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Node name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name must not contain spaces or the following special characters: * \&quot; &lt; &gt; \\ / ? : and |. The character . must not be used at the end of the name. 
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name must not contain spaces or the following special characters: * \" < > \\ / ? : and |. The character . must not be used at the end of the name. ")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Node nodeType(String nodeType) {
    
    this.nodeType = nodeType;
    return this;
  }

   /**
   * Get nodeType
   * @return nodeType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNodeType() {
    return nodeType;
  }


  public void setNodeType(String nodeType) {
    this.nodeType = nodeType;
  }


  public Node isFolder(Boolean isFolder) {
    
    this.isFolder = isFolder;
    return this;
  }

   /**
   * Get isFolder
   * @return isFolder
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsFolder() {
    return isFolder;
  }


  public void setIsFolder(Boolean isFolder) {
    this.isFolder = isFolder;
  }


  public Node isFile(Boolean isFile) {
    
    this.isFile = isFile;
    return this;
  }

   /**
   * Get isFile
   * @return isFile
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsFile() {
    return isFile;
  }


  public void setIsFile(Boolean isFile) {
    this.isFile = isFile;
  }


  public Node isLocked(Boolean isLocked) {
    
    this.isLocked = isLocked;
    return this;
  }

   /**
   * Get isLocked
   * @return isLocked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsLocked() {
    return isLocked;
  }


  public void setIsLocked(Boolean isLocked) {
    this.isLocked = isLocked;
  }


  public Node modifiedAt(OffsetDateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public Node modifiedByUser(UserInfo modifiedByUser) {
    
    this.modifiedByUser = modifiedByUser;
    return this;
  }

   /**
   * Get modifiedByUser
   * @return modifiedByUser
  **/
  @ApiModelProperty(required = true, value = "")

  public UserInfo getModifiedByUser() {
    return modifiedByUser;
  }


  public void setModifiedByUser(UserInfo modifiedByUser) {
    this.modifiedByUser = modifiedByUser;
  }


  public Node createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Node createdByUser(UserInfo createdByUser) {
    
    this.createdByUser = createdByUser;
    return this;
  }

   /**
   * Get createdByUser
   * @return createdByUser
  **/
  @ApiModelProperty(required = true, value = "")

  public UserInfo getCreatedByUser() {
    return createdByUser;
  }


  public void setCreatedByUser(UserInfo createdByUser) {
    this.createdByUser = createdByUser;
  }


  public Node parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParentId() {
    return parentId;
  }


  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public Node isLink(Boolean isLink) {
    
    this.isLink = isLink;
    return this;
  }

   /**
   * Get isLink
   * @return isLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsLink() {
    return isLink;
  }


  public void setIsLink(Boolean isLink) {
    this.isLink = isLink;
  }


  public Node isFavorite(Boolean isFavorite) {
    
    this.isFavorite = isFavorite;
    return this;
  }

   /**
   * Get isFavorite
   * @return isFavorite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsFavorite() {
    return isFavorite;
  }


  public void setIsFavorite(Boolean isFavorite) {
    this.isFavorite = isFavorite;
  }


  public Node isDirectLinkEnabled(Boolean isDirectLinkEnabled) {
    
    this.isDirectLinkEnabled = isDirectLinkEnabled;
    return this;
  }

   /**
   * Get isDirectLinkEnabled
   * @return isDirectLinkEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsDirectLinkEnabled() {
    return isDirectLinkEnabled;
  }


  public void setIsDirectLinkEnabled(Boolean isDirectLinkEnabled) {
    this.isDirectLinkEnabled = isDirectLinkEnabled;
  }


  public Node content(ContentInfo content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ContentInfo getContent() {
    return content;
  }


  public void setContent(ContentInfo content) {
    this.content = content;
  }


  public Node aspectNames(List<String> aspectNames) {
    
    this.aspectNames = aspectNames;
    return this;
  }

  public Node addAspectNamesItem(String aspectNamesItem) {
    if (this.aspectNames == null) {
      this.aspectNames = new ArrayList<String>();
    }
    this.aspectNames.add(aspectNamesItem);
    return this;
  }

   /**
   * Get aspectNames
   * @return aspectNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAspectNames() {
    return aspectNames;
  }


  public void setAspectNames(List<String> aspectNames) {
    this.aspectNames = aspectNames;
  }


  public Node properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getProperties() {
    return properties;
  }


  public void setProperties(Object properties) {
    this.properties = properties;
  }


  public Node allowableOperations(List<String> allowableOperations) {
    
    this.allowableOperations = allowableOperations;
    return this;
  }

  public Node addAllowableOperationsItem(String allowableOperationsItem) {
    if (this.allowableOperations == null) {
      this.allowableOperations = new ArrayList<String>();
    }
    this.allowableOperations.add(allowableOperationsItem);
    return this;
  }

   /**
   * Get allowableOperations
   * @return allowableOperations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAllowableOperations() {
    return allowableOperations;
  }


  public void setAllowableOperations(List<String> allowableOperations) {
    this.allowableOperations = allowableOperations;
  }


  public Node path(PathInfo path) {
    
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PathInfo getPath() {
    return path;
  }


  public void setPath(PathInfo path) {
    this.path = path;
  }


  public Node permissions(PermissionsInfo permissions) {
    
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PermissionsInfo getPermissions() {
    return permissions;
  }


  public void setPermissions(PermissionsInfo permissions) {
    this.permissions = permissions;
  }


  public Node definition(Definition definition) {
    
    this.definition = definition;
    return this;
  }

   /**
   * Get definition
   * @return definition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Definition getDefinition() {
    return definition;
  }


  public void setDefinition(Definition definition) {
    this.definition = definition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Node node = (Node) o;
    return Objects.equals(this.id, node.id) &&
        Objects.equals(this.name, node.name) &&
        Objects.equals(this.nodeType, node.nodeType) &&
        Objects.equals(this.isFolder, node.isFolder) &&
        Objects.equals(this.isFile, node.isFile) &&
        Objects.equals(this.isLocked, node.isLocked) &&
        Objects.equals(this.modifiedAt, node.modifiedAt) &&
        Objects.equals(this.modifiedByUser, node.modifiedByUser) &&
        Objects.equals(this.createdAt, node.createdAt) &&
        Objects.equals(this.createdByUser, node.createdByUser) &&
        Objects.equals(this.parentId, node.parentId) &&
        Objects.equals(this.isLink, node.isLink) &&
        Objects.equals(this.isFavorite, node.isFavorite) &&
        Objects.equals(this.isDirectLinkEnabled, node.isDirectLinkEnabled) &&
        Objects.equals(this.content, node.content) &&
        Objects.equals(this.aspectNames, node.aspectNames) &&
        Objects.equals(this.properties, node.properties) &&
        Objects.equals(this.allowableOperations, node.allowableOperations) &&
        Objects.equals(this.path, node.path) &&
        Objects.equals(this.permissions, node.permissions) &&
        Objects.equals(this.definition, node.definition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, nodeType, isFolder, isFile, isLocked, modifiedAt, modifiedByUser, createdAt, createdByUser, parentId, isLink, isFavorite, isDirectLinkEnabled, content, aspectNames, properties, allowableOperations, path, permissions, definition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Node {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeType: ").append(toIndentedString(nodeType)).append("\n");
    sb.append("    isFolder: ").append(toIndentedString(isFolder)).append("\n");
    sb.append("    isFile: ").append(toIndentedString(isFile)).append("\n");
    sb.append("    isLocked: ").append(toIndentedString(isLocked)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedByUser: ").append(toIndentedString(modifiedByUser)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdByUser: ").append(toIndentedString(createdByUser)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    isLink: ").append(toIndentedString(isLink)).append("\n");
    sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
    sb.append("    isDirectLinkEnabled: ").append(toIndentedString(isDirectLinkEnabled)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    aspectNames: ").append(toIndentedString(aspectNames)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    allowableOperations: ").append(toIndentedString(allowableOperations)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

