/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PermissionElement;

/**
 * PermissionsInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class PermissionsInfo {
  public static final String SERIALIZED_NAME_IS_INHERITANCE_ENABLED = "isInheritanceEnabled";
  @SerializedName(SERIALIZED_NAME_IS_INHERITANCE_ENABLED)
  private Boolean isInheritanceEnabled;

  public static final String SERIALIZED_NAME_INHERITED = "inherited";
  @SerializedName(SERIALIZED_NAME_INHERITED)
  private List<PermissionElement> inherited = null;

  public static final String SERIALIZED_NAME_LOCALLY_SET = "locallySet";
  @SerializedName(SERIALIZED_NAME_LOCALLY_SET)
  private List<PermissionElement> locallySet = null;

  public static final String SERIALIZED_NAME_SETTABLE = "settable";
  @SerializedName(SERIALIZED_NAME_SETTABLE)
  private List<String> settable = null;


  public PermissionsInfo isInheritanceEnabled(Boolean isInheritanceEnabled) {
    
    this.isInheritanceEnabled = isInheritanceEnabled;
    return this;
  }

   /**
   * Get isInheritanceEnabled
   * @return isInheritanceEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsInheritanceEnabled() {
    return isInheritanceEnabled;
  }


  public void setIsInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
  }


  public PermissionsInfo inherited(List<PermissionElement> inherited) {
    
    this.inherited = inherited;
    return this;
  }

  public PermissionsInfo addInheritedItem(PermissionElement inheritedItem) {
    if (this.inherited == null) {
      this.inherited = new ArrayList<PermissionElement>();
    }
    this.inherited.add(inheritedItem);
    return this;
  }

   /**
   * Get inherited
   * @return inherited
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PermissionElement> getInherited() {
    return inherited;
  }


  public void setInherited(List<PermissionElement> inherited) {
    this.inherited = inherited;
  }


  public PermissionsInfo locallySet(List<PermissionElement> locallySet) {
    
    this.locallySet = locallySet;
    return this;
  }

  public PermissionsInfo addLocallySetItem(PermissionElement locallySetItem) {
    if (this.locallySet == null) {
      this.locallySet = new ArrayList<PermissionElement>();
    }
    this.locallySet.add(locallySetItem);
    return this;
  }

   /**
   * Get locallySet
   * @return locallySet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PermissionElement> getLocallySet() {
    return locallySet;
  }


  public void setLocallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
  }


  public PermissionsInfo settable(List<String> settable) {
    
    this.settable = settable;
    return this;
  }

  public PermissionsInfo addSettableItem(String settableItem) {
    if (this.settable == null) {
      this.settable = new ArrayList<String>();
    }
    this.settable.add(settableItem);
    return this;
  }

   /**
   * Get settable
   * @return settable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSettable() {
    return settable;
  }


  public void setSettable(List<String> settable) {
    this.settable = settable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionsInfo permissionsInfo = (PermissionsInfo) o;
    return Objects.equals(this.isInheritanceEnabled, permissionsInfo.isInheritanceEnabled) &&
        Objects.equals(this.inherited, permissionsInfo.inherited) &&
        Objects.equals(this.locallySet, permissionsInfo.locallySet) &&
        Objects.equals(this.settable, permissionsInfo.settable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isInheritanceEnabled, inherited, locallySet, settable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionsInfo {\n");
    sb.append("    isInheritanceEnabled: ").append(toIndentedString(isInheritanceEnabled)).append("\n");
    sb.append("    inherited: ").append(toIndentedString(inherited)).append("\n");
    sb.append("    locallySet: ").append(toIndentedString(locallySet)).append("\n");
    sb.append("    settable: ").append(toIndentedString(settable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

