/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PermissionElement;

/**
 * PermissionsBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class PermissionsBody {
  public static final String SERIALIZED_NAME_IS_INHERITANCE_ENABLED = "isInheritanceEnabled";
  @SerializedName(SERIALIZED_NAME_IS_INHERITANCE_ENABLED)
  private Boolean isInheritanceEnabled;

  public static final String SERIALIZED_NAME_LOCALLY_SET = "locallySet";
  @SerializedName(SERIALIZED_NAME_LOCALLY_SET)
  private List<PermissionElement> locallySet = null;


  public PermissionsBody isInheritanceEnabled(Boolean isInheritanceEnabled) {
    
    this.isInheritanceEnabled = isInheritanceEnabled;
    return this;
  }

   /**
   * Get isInheritanceEnabled
   * @return isInheritanceEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsInheritanceEnabled() {
    return isInheritanceEnabled;
  }


  public void setIsInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
  }


  public PermissionsBody locallySet(List<PermissionElement> locallySet) {
    
    this.locallySet = locallySet;
    return this;
  }

  public PermissionsBody addLocallySetItem(PermissionElement locallySetItem) {
    if (this.locallySet == null) {
      this.locallySet = new ArrayList<PermissionElement>();
    }
    this.locallySet.add(locallySetItem);
    return this;
  }

   /**
   * Get locallySet
   * @return locallySet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PermissionElement> getLocallySet() {
    return locallySet;
  }


  public void setLocallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionsBody permissionsBody = (PermissionsBody) o;
    return Objects.equals(this.isInheritanceEnabled, permissionsBody.isInheritanceEnabled) &&
        Objects.equals(this.locallySet, permissionsBody.locallySet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isInheritanceEnabled, locallySet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionsBody {\n");
    sb.append("    isInheritanceEnabled: ").append(toIndentedString(isInheritanceEnabled)).append("\n");
    sb.append("    locallySet: ").append(toIndentedString(locallySet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

