/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Company;

/**
 * PersonBodyUpdate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class PersonBodyUpdate {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_SKYPE_ID = "skypeId";
  @SerializedName(SERIALIZED_NAME_SKYPE_ID)
  private String skypeId;

  public static final String SERIALIZED_NAME_GOOGLE_ID = "googleId";
  @SerializedName(SERIALIZED_NAME_GOOGLE_ID)
  private String googleId;

  public static final String SERIALIZED_NAME_INSTANT_MESSAGE_ID = "instantMessageId";
  @SerializedName(SERIALIZED_NAME_INSTANT_MESSAGE_ID)
  private String instantMessageId;

  public static final String SERIALIZED_NAME_JOB_TITLE = "jobTitle";
  @SerializedName(SERIALIZED_NAME_JOB_TITLE)
  private String jobTitle;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  public static final String SERIALIZED_NAME_COMPANY = "company";
  @SerializedName(SERIALIZED_NAME_COMPANY)
  private Company company;

  public static final String SERIALIZED_NAME_MOBILE = "mobile";
  @SerializedName(SERIALIZED_NAME_MOBILE)
  private String mobile;

  public static final String SERIALIZED_NAME_TELEPHONE = "telephone";
  @SerializedName(SERIALIZED_NAME_TELEPHONE)
  private String telephone;

  public static final String SERIALIZED_NAME_USER_STATUS = "userStatus";
  @SerializedName(SERIALIZED_NAME_USER_STATUS)
  private String userStatus;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_EMAIL_NOTIFICATIONS_ENABLED = "emailNotificationsEnabled";
  @SerializedName(SERIALIZED_NAME_EMAIL_NOTIFICATIONS_ENABLED)
  private Boolean emailNotificationsEnabled;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_OLD_PASSWORD = "oldPassword";
  @SerializedName(SERIALIZED_NAME_OLD_PASSWORD)
  private String oldPassword;

  public static final String SERIALIZED_NAME_ASPECT_NAMES = "aspectNames";
  @SerializedName(SERIALIZED_NAME_ASPECT_NAMES)
  private List<String> aspectNames = null;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Object properties;


  public PersonBodyUpdate firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public PersonBodyUpdate lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public PersonBodyUpdate description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PersonBodyUpdate email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public PersonBodyUpdate skypeId(String skypeId) {
    
    this.skypeId = skypeId;
    return this;
  }

   /**
   * Get skypeId
   * @return skypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSkypeId() {
    return skypeId;
  }


  public void setSkypeId(String skypeId) {
    this.skypeId = skypeId;
  }


  public PersonBodyUpdate googleId(String googleId) {
    
    this.googleId = googleId;
    return this;
  }

   /**
   * Get googleId
   * @return googleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGoogleId() {
    return googleId;
  }


  public void setGoogleId(String googleId) {
    this.googleId = googleId;
  }


  public PersonBodyUpdate instantMessageId(String instantMessageId) {
    
    this.instantMessageId = instantMessageId;
    return this;
  }

   /**
   * Get instantMessageId
   * @return instantMessageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstantMessageId() {
    return instantMessageId;
  }


  public void setInstantMessageId(String instantMessageId) {
    this.instantMessageId = instantMessageId;
  }


  public PersonBodyUpdate jobTitle(String jobTitle) {
    
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobTitle() {
    return jobTitle;
  }


  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }


  public PersonBodyUpdate location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public PersonBodyUpdate company(Company company) {
    
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Company getCompany() {
    return company;
  }


  public void setCompany(Company company) {
    this.company = company;
  }


  public PersonBodyUpdate mobile(String mobile) {
    
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMobile() {
    return mobile;
  }


  public void setMobile(String mobile) {
    this.mobile = mobile;
  }


  public PersonBodyUpdate telephone(String telephone) {
    
    this.telephone = telephone;
    return this;
  }

   /**
   * Get telephone
   * @return telephone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTelephone() {
    return telephone;
  }


  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }


  public PersonBodyUpdate userStatus(String userStatus) {
    
    this.userStatus = userStatus;
    return this;
  }

   /**
   * Get userStatus
   * @return userStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserStatus() {
    return userStatus;
  }


  public void setUserStatus(String userStatus) {
    this.userStatus = userStatus;
  }


  public PersonBodyUpdate enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public PersonBodyUpdate emailNotificationsEnabled(Boolean emailNotificationsEnabled) {
    
    this.emailNotificationsEnabled = emailNotificationsEnabled;
    return this;
  }

   /**
   * Get emailNotificationsEnabled
   * @return emailNotificationsEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEmailNotificationsEnabled() {
    return emailNotificationsEnabled;
  }


  public void setEmailNotificationsEnabled(Boolean emailNotificationsEnabled) {
    this.emailNotificationsEnabled = emailNotificationsEnabled;
  }


  public PersonBodyUpdate password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public PersonBodyUpdate oldPassword(String oldPassword) {
    
    this.oldPassword = oldPassword;
    return this;
  }

   /**
   * Get oldPassword
   * @return oldPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOldPassword() {
    return oldPassword;
  }


  public void setOldPassword(String oldPassword) {
    this.oldPassword = oldPassword;
  }


  public PersonBodyUpdate aspectNames(List<String> aspectNames) {
    
    this.aspectNames = aspectNames;
    return this;
  }

  public PersonBodyUpdate addAspectNamesItem(String aspectNamesItem) {
    if (this.aspectNames == null) {
      this.aspectNames = new ArrayList<String>();
    }
    this.aspectNames.add(aspectNamesItem);
    return this;
  }

   /**
   * Get aspectNames
   * @return aspectNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAspectNames() {
    return aspectNames;
  }


  public void setAspectNames(List<String> aspectNames) {
    this.aspectNames = aspectNames;
  }


  public PersonBodyUpdate properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getProperties() {
    return properties;
  }


  public void setProperties(Object properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonBodyUpdate personBodyUpdate = (PersonBodyUpdate) o;
    return Objects.equals(this.firstName, personBodyUpdate.firstName) &&
        Objects.equals(this.lastName, personBodyUpdate.lastName) &&
        Objects.equals(this.description, personBodyUpdate.description) &&
        Objects.equals(this.email, personBodyUpdate.email) &&
        Objects.equals(this.skypeId, personBodyUpdate.skypeId) &&
        Objects.equals(this.googleId, personBodyUpdate.googleId) &&
        Objects.equals(this.instantMessageId, personBodyUpdate.instantMessageId) &&
        Objects.equals(this.jobTitle, personBodyUpdate.jobTitle) &&
        Objects.equals(this.location, personBodyUpdate.location) &&
        Objects.equals(this.company, personBodyUpdate.company) &&
        Objects.equals(this.mobile, personBodyUpdate.mobile) &&
        Objects.equals(this.telephone, personBodyUpdate.telephone) &&
        Objects.equals(this.userStatus, personBodyUpdate.userStatus) &&
        Objects.equals(this.enabled, personBodyUpdate.enabled) &&
        Objects.equals(this.emailNotificationsEnabled, personBodyUpdate.emailNotificationsEnabled) &&
        Objects.equals(this.password, personBodyUpdate.password) &&
        Objects.equals(this.oldPassword, personBodyUpdate.oldPassword) &&
        Objects.equals(this.aspectNames, personBodyUpdate.aspectNames) &&
        Objects.equals(this.properties, personBodyUpdate.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, description, email, skypeId, googleId, instantMessageId, jobTitle, location, company, mobile, telephone, userStatus, enabled, emailNotificationsEnabled, password, oldPassword, aspectNames, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonBodyUpdate {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    skypeId: ").append(toIndentedString(skypeId)).append("\n");
    sb.append("    googleId: ").append(toIndentedString(googleId)).append("\n");
    sb.append("    instantMessageId: ").append(toIndentedString(instantMessageId)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    userStatus: ").append(toIndentedString(userStatus)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    emailNotificationsEnabled: ").append(toIndentedString(emailNotificationsEnabled)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    oldPassword: ").append(toIndentedString(oldPassword)).append("\n");
    sb.append("    aspectNames: ").append(toIndentedString(aspectNames)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

