/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.NetworkQuota;
import org.threeten.bp.OffsetDateTime;

/**
 * A network is the group of users and sites that belong to an organization. Networks are organized by email domain. When a user signs up for an Alfresco account , their email domain becomes their Home Network. 
 */
@ApiModel(description = "A network is the group of users and sites that belong to an organization. Networks are organized by email domain. When a user signs up for an Alfresco account , their email domain becomes their Home Network. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class PersonNetwork {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_HOME_NETWORK = "homeNetwork";
  @SerializedName(SERIALIZED_NAME_HOME_NETWORK)
  private Boolean homeNetwork;

  public static final String SERIALIZED_NAME_IS_ENABLED = "isEnabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  private Boolean isEnabled;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_PAID_NETWORK = "paidNetwork";
  @SerializedName(SERIALIZED_NAME_PAID_NETWORK)
  private Boolean paidNetwork;

  /**
   * Gets or Sets subscriptionLevel
   */
  @JsonAdapter(SubscriptionLevelEnum.Adapter.class)
  public enum SubscriptionLevelEnum {
    FREE("Free"),
    
    STANDARD("Standard"),
    
    ENTERPRISE("Enterprise");

    private String value;

    SubscriptionLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SubscriptionLevelEnum fromValue(String value) {
      for (SubscriptionLevelEnum b : SubscriptionLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SubscriptionLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubscriptionLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SubscriptionLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SubscriptionLevelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SUBSCRIPTION_LEVEL = "subscriptionLevel";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_LEVEL)
  private SubscriptionLevelEnum subscriptionLevel;

  public static final String SERIALIZED_NAME_QUOTAS = "quotas";
  @SerializedName(SERIALIZED_NAME_QUOTAS)
  private List<NetworkQuota> quotas = null;


  public PersonNetwork id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * This network&#39;s unique id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "This network's unique id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public PersonNetwork homeNetwork(Boolean homeNetwork) {
    
    this.homeNetwork = homeNetwork;
    return this;
  }

   /**
   * Is this the home network?
   * @return homeNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Is this the home network?")

  public Boolean getHomeNetwork() {
    return homeNetwork;
  }


  public void setHomeNetwork(Boolean homeNetwork) {
    this.homeNetwork = homeNetwork;
  }


  public PersonNetwork isEnabled(Boolean isEnabled) {
    
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Get isEnabled
   * @return isEnabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsEnabled() {
    return isEnabled;
  }


  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public PersonNetwork createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PersonNetwork paidNetwork(Boolean paidNetwork) {
    
    this.paidNetwork = paidNetwork;
    return this;
  }

   /**
   * Get paidNetwork
   * @return paidNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPaidNetwork() {
    return paidNetwork;
  }


  public void setPaidNetwork(Boolean paidNetwork) {
    this.paidNetwork = paidNetwork;
  }


  public PersonNetwork subscriptionLevel(SubscriptionLevelEnum subscriptionLevel) {
    
    this.subscriptionLevel = subscriptionLevel;
    return this;
  }

   /**
   * Get subscriptionLevel
   * @return subscriptionLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SubscriptionLevelEnum getSubscriptionLevel() {
    return subscriptionLevel;
  }


  public void setSubscriptionLevel(SubscriptionLevelEnum subscriptionLevel) {
    this.subscriptionLevel = subscriptionLevel;
  }


  public PersonNetwork quotas(List<NetworkQuota> quotas) {
    
    this.quotas = quotas;
    return this;
  }

  public PersonNetwork addQuotasItem(NetworkQuota quotasItem) {
    if (this.quotas == null) {
      this.quotas = new ArrayList<NetworkQuota>();
    }
    this.quotas.add(quotasItem);
    return this;
  }

   /**
   * Get quotas
   * @return quotas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<NetworkQuota> getQuotas() {
    return quotas;
  }


  public void setQuotas(List<NetworkQuota> quotas) {
    this.quotas = quotas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonNetwork personNetwork = (PersonNetwork) o;
    return Objects.equals(this.id, personNetwork.id) &&
        Objects.equals(this.homeNetwork, personNetwork.homeNetwork) &&
        Objects.equals(this.isEnabled, personNetwork.isEnabled) &&
        Objects.equals(this.createdAt, personNetwork.createdAt) &&
        Objects.equals(this.paidNetwork, personNetwork.paidNetwork) &&
        Objects.equals(this.subscriptionLevel, personNetwork.subscriptionLevel) &&
        Objects.equals(this.quotas, personNetwork.quotas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, homeNetwork, isEnabled, createdAt, paidNetwork, subscriptionLevel, quotas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonNetwork {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    homeNetwork: ").append(toIndentedString(homeNetwork)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    paidNetwork: ").append(toIndentedString(paidNetwork)).append("\n");
    sb.append("    subscriptionLevel: ").append(toIndentedString(subscriptionLevel)).append("\n");
    sb.append("    quotas: ").append(toIndentedString(quotas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

