/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.RatingAggregate;
import org.threeten.bp.OffsetDateTime;

/**
 * A person can rate an item of content by liking it. They can also remove their like of an item of content. API methods exist to get a list of ratings and to add a new rating. 
 */
@ApiModel(description = "A person can rate an item of content by liking it. They can also remove their like of an item of content. API methods exist to get a list of ratings and to add a new rating. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class Rating {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_AGGREGATE = "aggregate";
  @SerializedName(SERIALIZED_NAME_AGGREGATE)
  private RatingAggregate aggregate;

  public static final String SERIALIZED_NAME_RATED_AT = "ratedAt";
  @SerializedName(SERIALIZED_NAME_RATED_AT)
  private OffsetDateTime ratedAt;

  public static final String SERIALIZED_NAME_MY_RATING = "myRating";
  @SerializedName(SERIALIZED_NAME_MY_RATING)
  private String myRating;


  public Rating id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Rating aggregate(RatingAggregate aggregate) {
    
    this.aggregate = aggregate;
    return this;
  }

   /**
   * Get aggregate
   * @return aggregate
  **/
  @ApiModelProperty(required = true, value = "")

  public RatingAggregate getAggregate() {
    return aggregate;
  }


  public void setAggregate(RatingAggregate aggregate) {
    this.aggregate = aggregate;
  }


  public Rating ratedAt(OffsetDateTime ratedAt) {
    
    this.ratedAt = ratedAt;
    return this;
  }

   /**
   * Get ratedAt
   * @return ratedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getRatedAt() {
    return ratedAt;
  }


  public void setRatedAt(OffsetDateTime ratedAt) {
    this.ratedAt = ratedAt;
  }


  public Rating myRating(String myRating) {
    
    this.myRating = myRating;
    return this;
  }

   /**
   * The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar.
   * @return myRating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar.")

  public String getMyRating() {
    return myRating;
  }


  public void setMyRating(String myRating) {
    this.myRating = myRating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rating rating = (Rating) o;
    return Objects.equals(this.id, rating.id) &&
        Objects.equals(this.aggregate, rating.aggregate) &&
        Objects.equals(this.ratedAt, rating.ratedAt) &&
        Objects.equals(this.myRating, rating.myRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, aggregate, ratedAt, myRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rating {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    aggregate: ").append(toIndentedString(aggregate)).append("\n");
    sb.append("    ratedAt: ").append(toIndentedString(ratedAt)).append("\n");
    sb.append("    myRating: ").append(toIndentedString(myRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

