/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RatingAggregate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class RatingAggregate {
  public static final String SERIALIZED_NAME_NUMBER_OF_RATINGS = "numberOfRatings";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_RATINGS)
  private Integer numberOfRatings;

  public static final String SERIALIZED_NAME_AVERAGE = "average";
  @SerializedName(SERIALIZED_NAME_AVERAGE)
  private Integer average;


  public RatingAggregate numberOfRatings(Integer numberOfRatings) {
    
    this.numberOfRatings = numberOfRatings;
    return this;
  }

   /**
   * Get numberOfRatings
   * @return numberOfRatings
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getNumberOfRatings() {
    return numberOfRatings;
  }


  public void setNumberOfRatings(Integer numberOfRatings) {
    this.numberOfRatings = numberOfRatings;
  }


  public RatingAggregate average(Integer average) {
    
    this.average = average;
    return this;
  }

   /**
   * Get average
   * @return average
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAverage() {
    return average;
  }


  public void setAverage(Integer average) {
    this.average = average;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingAggregate ratingAggregate = (RatingAggregate) o;
    return Objects.equals(this.numberOfRatings, ratingAggregate.numberOfRatings) &&
        Objects.equals(this.average, ratingAggregate.average);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfRatings, average);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingAggregate {\n");
    sb.append("    numberOfRatings: ").append(toIndentedString(numberOfRatings)).append("\n");
    sb.append("    average: ").append(toIndentedString(average)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

