/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RatingBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T14:17:06.136707300+08:00[Asia/Ulaanbaatar]")
public class RatingBody {
  /**
   * The rating scheme type. Possible values are likes and fiveStar.
   */
  @JsonAdapter(IdEnum.Adapter.class)
  public enum IdEnum {
    LIKES("likes"),
    
    FIVESTAR("fiveStar");

    private String value;

    IdEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IdEnum fromValue(String value) {
      for (IdEnum b : IdEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IdEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IdEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IdEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IdEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private IdEnum id = IdEnum.LIKES;

  public static final String SERIALIZED_NAME_MY_RATING = "myRating";
  @SerializedName(SERIALIZED_NAME_MY_RATING)
  private String myRating;


  public RatingBody id(IdEnum id) {
    
    this.id = id;
    return this;
  }

   /**
   * The rating scheme type. Possible values are likes and fiveStar.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The rating scheme type. Possible values are likes and fiveStar.")

  public IdEnum getId() {
    return id;
  }


  public void setId(IdEnum id) {
    this.id = id;
  }


  public RatingBody myRating(String myRating) {
    
    this.myRating = myRating;
    return this;
  }

   /**
   * The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar
   * @return myRating
  **/
  @ApiModelProperty(required = true, value = "The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar")

  public String getMyRating() {
    return myRating;
  }


  public void setMyRating(String myRating) {
    this.myRating = myRating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingBody ratingBody = (RatingBody) o;
    return Objects.equals(this.id, ratingBody.id) &&
        Objects.equals(this.myRating, ratingBody.myRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, myRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingBody {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    myRating: ").append(toIndentedString(myRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

